package com.example.asus.downloaddemo.common.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.asus.downloaddemo.common.bean.DownLoadInfo;
import com.example.asus.downloaddemo.common.bean.AppInfo;

import com.example.asus.downloaddemo.common.bean.DownLoadInfoDao;
import com.example.asus.downloaddemo.common.bean.AppInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downLoadInfoDaoConfig;
    private final DaoConfig appInfoDaoConfig;

    private final DownLoadInfoDao downLoadInfoDao;
    private final AppInfoDao appInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downLoadInfoDaoConfig = daoConfigMap.get(DownLoadInfoDao.class).clone();
        downLoadInfoDaoConfig.initIdentityScope(type);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        downLoadInfoDao = new DownLoadInfoDao(downLoadInfoDaoConfig, this);
        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);

        registerDao(DownLoadInfo.class, downLoadInfoDao);
        registerDao(AppInfo.class, appInfoDao);
    }
    
    public void clear() {
        downLoadInfoDaoConfig.clearIdentityScope();
        appInfoDaoConfig.clearIdentityScope();
    }

    public DownLoadInfoDao getDownLoadInfoDao() {
        return downLoadInfoDao;
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

}
